
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 10.1.03 EDK_K_SP3.6
* DO NOT EDIT.
*
* Copyright (c) 2005 Xilinx, Inc.  All rights reserved. 
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xlltemac.h"

/*
* The configuration table for devices
*/

XLlTemac_Config XLlTemac_ConfigTable[] =
{
	{
		XPAR_LLTEMAC_0_DEVICE_ID,
		XPAR_LLTEMAC_0_BASEADDR,
		XPAR_LLTEMAC_0_TXCSUM,
		XPAR_LLTEMAC_0_RXCSUM,
		XPAR_LLTEMAC_0_PHY_TYPE,
		XPAR_LLTEMAC_0_INTR,
		XPAR_LLTEMAC_0_LLINK_CONNECTED_TYPE,
		XPAR_LLTEMAC_0_LLINK_CONNECTED_BASEADDR,
		0xFF,
		XPAR_LLTEMAC_0_LLINK_CONNECTED_DMARX_INTR,
		XPAR_LLTEMAC_0_LLINK_CONNECTED_DMATX_INTR
	}
};

