######################################################################
##
## Filename: sync_trigger.udo
## Created on: Thu Dec 01 02:04:16 PM CET 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
