######################################################################
##
## Filename: async_trigger_tb.udo
## Created on: Fri Aug 26 01:09:03 PM CEST 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
