######################################################################
##
## Filename: fill_ones_tb.udo
## Created on: Thu Sep 15 10:59:03 AM CEST 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
