######################################################################
##
## Filename: rate_counter.udo
## Created on: Tue Jun 14 02:23:13 PM CEST 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
