######################################################################
##
## Filename: receiver_control_tb.udo
## Created on: Wed Aug 17 11:31:57 AM CEST 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
