######################################################################
##
## Filename: TB_udp.udo
## Created on: Thu Jun 09 02:39:12 PM CEST 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
