######################################################################
##
## Filename: udp_rec_tb.udo
## Created on: Mon Aug 15 03:23:35 PM CEST 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
