######################################################################
##
## Filename: udp_rec.udo
## Created on: Mon Aug 15 04:12:57 PM CEST 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
