######################################################################
##
## Filename: v5_emac_v1_5_example_design.udo
## Created on: Thu Jun 09 02:18:10 PM CEST 2011
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
